classlar/classlar/Models/StockControlModel.cs
namespace classlar.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using classlar.Classes;

    public partial class StockControlModel : DbContext
    {
        public StockControlModel()
            : base("name=StockControlModel")
        {
        }

        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }
}

classlar/classlar/Controllers/CustomerController.cs
using classlar.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace classlar.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateCustomer()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateCustomer(Customer entity)
        {
            DbFactory.DbConnection.Customers.Add(entity);
            DbFactory.DbConnection.SaveChanges();
            return View();
        }
        public ActionResult List()
        {
            return View();
        }
    }
}

classlar/classlar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace classlar.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

classlar/classlar/Controllers/LotController.cs
using classlar.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace classlar.Controllers
{
    public class LotController : Controller
    {
        // GET: Lot
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateLot()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateLot(Lot entity)
        {
            return View();
        }
        
        public ActionResult List()
        {
            return View();
        }
    }
}

classlar/classlar/Controllers/OrderController.cs
using classlar.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace classlar.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateOrder()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateOrder(Order entity)
        {
            return View();
        }
        public ActionResult List()
        {
            return View();
        }
    }
}

classlar/classlar/Controllers/ProductController.cs
using classlar.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace classlar.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateProduct()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateProduct(Product entity)
        {
            return View();
        }
        public ActionResult List()
        {
            return View();
        }
    }
}

classlar/classlar/Controllers/StockController.cs
using classlar.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace classlar.Controllers
{
    public class StockController : Controller
    {
        // GET: Stock
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateStock()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateStock(Stock entity)
        {
            return View();
        }
        public ActionResult List()
        {
            return View();
        }
    }
}

classlar/classlar/Controllers/VendorController.cs
using classlar.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace classlar.Controllers
{
    public class VendorController : Controller
    {
        // GET: Vendor
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateVendor()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateVendor(Vendor entity)
        {
            return View();
        }
        public ActionResult List()
        {
            return View();
        }
    }
}

classlar/classlar/Views/Customer/CreateCustomer.cshtml
@model classlar.Classes.Customer

@{
    ViewBag.Title = "CreateCustomer";
}

<h2>CreateCustomer</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CargoNameCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CargoNameCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CargoNameCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Loan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Loan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalAmountOfMoney, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalAmountOfMoney, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalAmountOfMoney, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalAmountOfNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalAmountOfNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalAmountOfNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

classlar/classlar/Views/Customer/List.cshtml
@model IEnumerable<classlar.Classes.Customer>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CargoNameCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Loan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalAmountOfMoney)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalAmountOfNumber)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerPhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CargoNameCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Loan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalAmountOfMoney)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalAmountOfNumber)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CustomerCode }) |
            @Html.ActionLink("Details", "Details", new { id=item.CustomerCode }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CustomerCode })
        </td>
    </tr>
}

</table>

classlar/classlar/Views/Lot/CreateLot.cshtml
@model classlar.Classes.Lot

@{
    ViewBag.Title = "CreateLot";
}

<h2>CreateLot</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lot</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LotQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LotQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LotQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

classlar/classlar/Views/Lot/List.cshtml
@model IEnumerable<classlar.Classes.Lot>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LotQuantity)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LotQuantity)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LotId }) |
            @Html.ActionLink("Details", "Details", new { id=item.LotId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LotId })
        </td>
    </tr>
}

</table>

classlar/classlar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ERP</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Main Page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- Customer -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Customer
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li class="dropdown-item">
                                @Html.ActionLink("Create Customer", "CreateCustomer", "Customer", new { area = "" }, new { @class = "dropdown-item" })
                            </li>
                            <li class="dropdown-item">
                                @Html.ActionLink("List Customers", "List", "Customer", new { area = "" }, new { @class = "dropdown-item" })
                            </li>
                        </ul>
                    </li>
                    <!-- Order -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Order
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li class="dropdown-item">@Html.ActionLink("Create Order", "CreateOrder", "Order", new { area = "" }, new { @class = "dropdown-item" })</li>
                            <li class="dropdown-item">@Html.ActionLink("List Orders", "List", "Order", new { area = "" }, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>
                    <!-- Product -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Product
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li class="nav-item">@Html.ActionLink("Create Product", "CreateProduct", "Product", new { area = "" }, new { @class = "dropdown-item" })</li>
                            <li class="nav-item">@Html.ActionLink("List Products", "List", "Product", new { area = "" }, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>
                    <!-- Vendor -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Vendor
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li class="nav-item">@Html.ActionLink("Create Vendor", "CreateVendor", "Vendor", new { area = "" }, new { @class = "dropdown-item" })</li>
                            <li class="nav-item">@Html.ActionLink("List Vendors", "List", "Vendor", new { area = "" }, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>
                    <!-- Stock -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Stock
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li class="nav-item">@Html.ActionLink("Create Stock", "CreateOrder", "Stock", new { area = "" }, new { @class = "dropdown-item" })</li>
                            <li class="nav-item">@Html.ActionLink("List Stock", "List", "Stock", new { area = "" }, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>
                    <!-- Lot -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Lot
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <li class="nav-item">@Html.ActionLink("Create Lot", "CreateLot", "Lot", new { area = "" }, new { @class = "dropdown-item" })</li>
                            <li class="nav-item">@Html.ActionLink("List Lot", "List", "Lot", new { area = "" }, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

classlar/classlar/Views/Stock/CreateStock.cshtml
@model classlar.Classes.Stock

@{
    ViewBag.Title = "CreateStock";
}

<h2>CreateStock</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Stock</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CountOfProduct, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CountOfProduct, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CountOfProduct, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

classlar/classlar/Views/Stock/List.cshtml
@model IEnumerable<classlar.Classes.Stock>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CountOfProduct)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CountOfProduct)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.StockId }) |
            @Html.ActionLink("Details", "Details", new { id=item.StockId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.StockId })
        </td>
    </tr>
}

</table>

classlar/classlar/Views/Vendor/CreateVendor.cshtml
@model classlar.Classes.Vendor

@{
    ViewBag.Title = "CreateVendor";
}

<h2>CreateVendor</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vendor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VendorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VendorAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VendorEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

classlar/classlar/Views/Vendor/List.cshtml
@model IEnumerable<classlar.Classes.Vendor>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VendorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VendorAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VendorEmail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VendorName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VendorAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VendorEmail)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.VendorId }) |
            @Html.ActionLink("Details", "Details", new { id=item.VendorId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.VendorId })
        </td>
    </tr>
}

</table>